<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJe7MmZV\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJe7MmZV/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJe7MmZV.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJe7MmZV\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJe7MmZV\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Je7MmZV',
    'container.build_id' => '8bfaeada',
    'container.build_time' => 1536296437,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJe7MmZV');
