<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYLS8FGu\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYLS8FGu/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYLS8FGu.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYLS8FGu\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYLS8FGu\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'YLS8FGu',
    'container.build_id' => '113dea1a',
    'container.build_time' => 1534932263,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYLS8FGu');
