<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6cxy1kx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6cxy1kx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6cxy1kx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6cxy1kx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container6cxy1kx\srcDevDebugProjectContainer(array(
    'container.build_hash' => '6cxy1kx',
    'container.build_id' => 'e01925c3',
    'container.build_time' => 1536140157,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6cxy1kx');
