<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nexy_slack.client' shared service.

return $this->services['nexy_slack.client'] = new \Nexy\Slack\Client($this->getEnv('string:SLACK_WEBHOOK_ENDPOINT'), $this->parameters['nexy_slack.config'], ($this->services['httplug.client'] ?? $this->load('getHttplug_ClientService.php')));
