<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'SensioLabs\Security\Command\SecurityCheckerCommand' shared service.

$this->privates['SensioLabs\Security\Command\SecurityCheckerCommand'] = $instance = new \SensioLabs\Security\Command\SecurityCheckerCommand(new \SensioLabs\Security\SecurityChecker());

$instance->setName('security:check');

return $instance;
