<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nexy_slack.client' shared service.

include_once $this->targetDirs[3].'\\vendor\\nexylan\\slack\\src\\Client.php';

return $this->services['nexy_slack.client'] = new \Nexy\Slack\Client('https://hooks.slack.com/services/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', $this->parameters['nexy_slack.config'], ($this->services['httplug.client'] ?? $this->load('getHttplug_ClientService.php')));
