<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\SlackClient' shared autowired service.

return $this->privates['App\Service\SlackClient'] = new \App\Service\SlackClient(($this->services['nexy_slack.client'] ?? $this->load('getNexySlack_ClientService.php')));
