<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'httplug.uri_factory' shared service.

include_once $this->targetDirs[3].'\\vendor\\php-http\\discovery\\src\\UriFactoryDiscovery.php';

return $this->services['httplug.uri_factory'] = \Http\Discovery\UriFactoryDiscovery::find();
