<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MT1r.sI' shared service.

return $this->privates['.service_locator.MT1r.sI'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('isDebug' => function () {
    return ($this->privates['.value.C_5.39h'] ?? $this->load('get_Value_C5_39hService.php'));
}, 'markdownHelper' => function (): \App\Service\MarkdownHelper {
    return ($this->privates['App\Service\MarkdownHelper'] ?? $this->load('getMarkdownHelperService.php'));
}));
