<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rAs6Sew' shared service.

return $this->privates['.service_locator.rAs6Sew'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('markdownHelper' => function (): \App\Service\MarkdownHelper {
    return ($this->privates['App\Service\MarkdownHelper'] ?? $this->load('getMarkdownHelperService.php'));
}, 'slack' => function (): \App\Service\SlackClient {
    return ($this->privates['App\Service\SlackClient'] ?? $this->load('getSlackClientService.php'));
}));
