<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

$this->factories['sonata.admin.orm.filter.type.time'] = function () {
    // Returns the public 'sonata.admin.orm.filter.type.time' service.

    return new \Sonata\DoctrineORMAdminBundle\Filter\TimeFilter();
};

return $this->factories['sonata.admin.orm.filter.type.time']();
