<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ArticleController' shared autowired service.

$this->services['App\Controller\ArticleController'] = $instance = new \App\Controller\ArticleController(true, ($this->services['nexy_slack.client'] ?? $this->load('getNexySlack_ClientService.php')));

$instance->setContainer(($this->privates['.service_locator.ychIlgF'] ?? $this->load('get_ServiceLocator_YchIlgFService.php'))->withContext('App\\Controller\\ArticleController', $this));

return $instance;
