<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

$this->factories['sonata.admin.orm.filter.type.model_autocomplete'] = function () {
    // Returns the public 'sonata.admin.orm.filter.type.model_autocomplete' service.

    return new \Sonata\DoctrineORMAdminBundle\Filter\ModelAutocompleteFilter();
};

return $this->factories['sonata.admin.orm.filter.type.model_autocomplete']();
