<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.form.type.collection' shared service.

return $this->privates['sonata.core.form.type.collection'] = new \Sonata\CoreBundle\Form\Type\CollectionType();
